apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-app
  namespace: vvennela
  labels:
    app: bms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
      - name: bms-container
        image: vennela355/bookmyshow:latest 
        ports:
        - containerPort: 3000